name: build

on:
  push:
    branches: [main]

env:
  AZURE_WEBAPP_NAME: 'SICI-WebApp'
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  DOTNET_VERSION: '8.0.X'

jobs:
    build:
      name: Construye la aplicaci贸n
      runs-on: ubuntu-latest
      steps:
        - name: Recupera el c贸digo fuente
          uses: actions/checkout@v4
        - name: Instala .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{env.DOTNET_VERSION}}
        - name: Instala las dependencias del proyecto
          run: dotnet restore src/SICI-WebApp/SICI-WebApp.sln

        - name: Construye la aplicaci贸n
          run: dotnet build --configuration Release --no-restore
        
        - name: Publica la aplicaci贸n
          run: dotnet publish --configuration Release --no-build --property:PublishDir='${{env.AZURE_WEBAPP_PACKAGE_PATH}}'